# Test installed the plugin on supported Python versions.
name: Usage

on: [push]

jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "pypy3"]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install --no-deps "."
          pip install -r requirements.txt
          pip install -r tests/requirements.txt
          pip freeze
      - name: Test suite
        run: |
          pytest -v tests
